import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          A(),
        ]),
      ),
    );
  }
}

class A extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 1119,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 852,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/393x852"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 393,
                  height: 1119,
                  decoration: BoxDecoration(
                    color: Colors.black.withOpacity(0.3799999952316284),
                  ),
                ),
              ),
              Positioned(
                left: 217,
                top: 306,
                child: Container(
                  width: 191,
                  height: 182,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF77FF04), Color(0xFF347C3D)],
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: -21,
                top: 176,
                child: Container(
                  width: 191,
                  height: 182,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFF04FF47), Color(0x5100FF1D)],
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: -43,
                top: 416,
                child: Container(
                  width: 191,
                  height: 182,
                  decoration: ShapeDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [Color(0xFFA3E567), Color(0x516CF5A5)],
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 476,
                child: Container(
                  width: 354,
                  height: 618,
                  decoration: BoxDecoration(color: Color(0xFF131010)),
                ),
              ),
              Positioned(
                left: 120,
                top: 294,
                child: Container(
                  width: 155,
                  height: 182,
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.15, -0.99),
                      end: Alignment(-0.15, 0.99),
                      colors: [Color(0xFF131010), Color(0xFF080808)],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 223,
                top: 396,
                child: Container(
                  width: 144,
                  height: 80,
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.50, -0.86),
                      end: Alignment(-0.5, 0.86),
                      colors: [Color(0xFF131010), Colors.black],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 423,
                child: Container(
                  width: 155,
                  height: 53,
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(-0.87, -0.49),
                      end: Alignment(0.87, 0.49),
                      colors: [Color(0xFF131010), Colors.black],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 154,
                top: 302,
                child: SizedBox(
                  width: 88,
                  height: 18,
                  child: SizedBox(
                    width: 88,
                    height: 18,
                    child: Text(
                      'Руфат герой',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 14,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w700,
                        height: 1.29,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 109,
                top: 74,
                child: Text(
                  'Таблица лидеров',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white.withOpacity(0.6499999761581421),
                    fontSize: 20,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                    height: 0.90,
                  ),
                ),
              ),
              Positioned(
                left: 239,
                top: 402,
                child: SizedBox(
                  width: 119,
                  height: 18,
                  child: SizedBox(
                    width: 119,
                    height: 18,
                    child: Text(
                      'Данжуан',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 11,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w700,
                        height: 1.64,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 75,
                top: 428,
                child: SizedBox(
                  width: 81,
                  height: 13,
                  child: SizedBox(
                    width: 81,
                    height: 13,
                    child: Text(
                      'Бекжан чорни',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 11,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w700,
                        height: 1.64,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 115,
                top: 142,
                child: Container(
                  width: 164,
                  height: 164,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(width: 2, color: Color(0xFFFECB2E)),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 115,
                top: 142,
                child: Container(
                  width: 164,
                  height: 164,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(width: 2, color: Color(0xFFFECB2E)),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 354,
                top: 401,
                child: Transform(
                  transform: Matrix4.identity()
                    ..translate(0.0, 0.0)
                    ..rotateZ(-1.57),
                  child: Container(
                    width: 112,
                    height: 112,
                    decoration: ShapeDecoration(
                      shape: OvalBorder(
                        side: BorderSide(width: 2, color: Colors.white),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 126,
                top: 153,
                child: Container(
                  width: 141,
                  height: 141,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/141x141"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 220,
                top: 244,
                child: Container(
                  width: 43.15,
                  height: 58,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 5.57,
                        top: 22.27,
                        child: Container(
                          width: 33.03,
                          height: 35.73,
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 43.15,
                          height: 43.15,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 43.15,
                                  height: 43.15,
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 46.34,
                                        height: 46.34,
                                        child: Stack(),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 2.02,
                                top: 2.02,
                                child: Container(
                                  width: 39.10,
                                  height: 39.10,
                                  padding: const EdgeInsets.only(
                                      top: 11.52, bottom: 12.31),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 8.28,
                                        height: 15.27,
                                        child: Stack(),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 155,
                top: 348,
                child: Container(
                  width: 84,
                  height: 22.74,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          decoration: ShapeDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(1.00, 0.00),
                              end: Alignment(-1, 0),
                              colors: [Color(0xFFFFC000), Color(0xFFFE8F2E)],
                            ),
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(6)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 11,
                        top: 4,
                        child: SizedBox(
                          width: 61,
                          height: 13,
                          child: SizedBox(
                            width: 61,
                            height: 13,
                            child: Text(
                              'Одно целое с природой',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFFAA6800),
                                fontSize: 7,
                                fontFamily: 'Roboto',
                                fontWeight: FontWeight.w700,
                                height: 1,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 66,
                top: 331,
                child: Container(
                  width: 98,
                  height: 98,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 6,
                        top: 6,
                        child: Container(
                          width: 86,
                          height: 86,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/86x86"),
                              fit: BoxFit.fill,
                            ),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Transform(
                          transform: Matrix4.identity()
                            ..translate(0.0, 0.0)
                            ..rotateZ(1.57),
                          child: Container(
                            width: 98,
                            height: 98,
                            decoration: ShapeDecoration(
                              shape: OvalBorder(
                                side: BorderSide(
                                    width: 2, color: Color(0xFFFF9832)),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 257,
                top: 448,
                child: Container(
                  width: 84,
                  height: 22.74,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          decoration: ShapeDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(1.00, 0.00),
                              end: Alignment(-1, 0),
                              colors: [Color(0xFFFFC000), Color(0xFFFE8F2E)],
                            ),
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(6)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 8,
                        top: 4,
                        child: SizedBox(
                          width: 68,
                          height: 10,
                          child: SizedBox(
                            width: 68,
                            height: 10,
                            child: Text(
                              'Настоящий герой',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFFAA6800),
                                fontSize: 8,
                                fontFamily: 'Roboto',
                                fontWeight: FontWeight.w700,
                                height: 1.75,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 101,
                top: 448,
                child: Container(
                  width: 84,
                  height: 22.74,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          decoration: ShapeDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(1.00, 0.00),
                              end: Alignment(-1, 0),
                              colors: [Color(0xFF6A00FF), Color(0xFFAA2EFE)],
                            ),
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(6)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 5,
                        child: SizedBox(
                          width: 51.16,
                          height: 8.21,
                          child: SizedBox(
                            width: 51.16,
                            height: 8.21,
                            child: Text(
                              'Фотограф',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFF2D00AA),
                                fontSize: 9,
                                fontFamily: 'Roboto',
                                fontWeight: FontWeight.w700,
                                height: 1.56,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 269,
                top: 423,
                child: Stack(
                  children: [
                    Positioned(
                      left: 14,
                      top: 2,
                      child: Text(
                        '500млн',
                        style: TextStyle(
                          color: Color(0xFF666666),
                          fontSize: 12,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w400,
                          height: 0.88,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 171,
                top: 323,
                child: Stack(
                  children: [
                    Positioned(
                      left: 14,
                      top: 2,
                      child: Text(
                        '1млрд',
                        style: TextStyle(
                          color: Color(0xFF666666),
                          fontSize: 12,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w400,
                          height: 0.88,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 42,
                top: 451,
                child: Stack(
                  children: [
                    Positioned(
                      left: 13,
                      top: 3,
                      child: Text(
                        '322млн',
                        style: TextStyle(
                          color: Color(0xFF666666),
                          fontSize: 11,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w400,
                          height: 0.88,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 40,
                top: 494,
                child: Container(
                  width: 327,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 243,
                        top: 6,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 84,
                                  height: 22.74,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(1.00, 0.00),
                                      end: Alignment(-1, 0),
                                      colors: [
                                        Color(0xFF7003FF),
                                        Color(0xFFA92DFE)
                                      ],
                                    ),
                                    shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(6)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 8,
                                top: 5,
                                child: SizedBox(
                                  width: 68,
                                  height: 11,
                                  child: SizedBox(
                                    width: 68,
                                    height: 11,
                                    child: Text(
                                      'Друид',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF3500AD),
                                        fontSize: 10,
                                        fontFamily: 'Roboto',
                                        fontWeight: FontWeight.w700,
                                        height: 1.40,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 180,
                        top: 11,
                        child: Container(
                          width: 56,
                          height: 16,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 14,
                                top: 3,
                                child: Text(
                                  '232млн',
                                  style: TextStyle(
                                    color: Color(0xFF666666),
                                    fontSize: 11,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.88,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 172,
                          height: 37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 65,
                                top: 10,
                                child: SizedBox(
                                  width: 107,
                                  height: 13,
                                  child: SizedBox(
                                    width: 107,
                                    height: 13,
                                    child: Text(
                                      'Machinegunkelly69',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.64,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 10,
                                child: SizedBox(
                                  width: 12,
                                  height: 13,
                                  child: SizedBox(
                                    width: 12,
                                    height: 13,
                                    child: Text(
                                      '4.',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 12,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.50,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 20,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 37,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://placehold.co/37x37"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 543,
                child: Container(
                  width: 327,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 243,
                        top: 6,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 84,
                                  height: 22.74,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(1.00, 0.00),
                                      end: Alignment(-1, 0),
                                      colors: [
                                        Color(0xFFCECECE),
                                        Color(0xFF7E7E7E)
                                      ],
                                    ),
                                    shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(6)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 8,
                                top: 5,
                                child: SizedBox(
                                  width: 68,
                                  height: 11,
                                  child: SizedBox(
                                    width: 68,
                                    height: 11,
                                    child: Text(
                                      'Новичок',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF8F8D8D),
                                        fontSize: 10,
                                        fontFamily: 'Roboto',
                                        fontWeight: FontWeight.w700,
                                        height: 1.40,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 180,
                        top: 11,
                        child: Container(
                          width: 54,
                          height: 16,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 14,
                                top: 3,
                                child: Text(
                                  '167млн',
                                  style: TextStyle(
                                    color: Color(0xFF666666),
                                    fontSize: 11,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.88,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 172,
                          height: 37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 65,
                                top: 10,
                                child: SizedBox(
                                  width: 107,
                                  height: 13,
                                  child: SizedBox(
                                    width: 107,
                                    height: 13,
                                    child: Text(
                                      'chico lachowski',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.64,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 10,
                                child: SizedBox(
                                  width: 12,
                                  height: 13,
                                  child: SizedBox(
                                    width: 12,
                                    height: 13,
                                    child: Text(
                                      '5.',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 12,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.50,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 20,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 37,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://placehold.co/37x37"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 592,
                child: Container(
                  width: 327,
                  height: 37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 243,
                        top: 6,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFF666666)),
                              borderRadius: BorderRadius.circular(6),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 184,
                        top: 11,
                        child: Container(
                          width: 50,
                          height: 16,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 15,
                                top: 3,
                                child: Text(
                                  '56млн',
                                  style: TextStyle(
                                    color: Color(0xFF666666),
                                    fontSize: 11,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.88,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 172,
                          height: 37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 65,
                                top: 10,
                                child: SizedBox(
                                  width: 107,
                                  height: 13,
                                  child: SizedBox(
                                    width: 107,
                                    height: 13,
                                    child: Text(
                                      'Ya dobriy',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.64,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 10,
                                child: SizedBox(
                                  width: 12,
                                  height: 13,
                                  child: SizedBox(
                                    width: 12,
                                    height: 13,
                                    child: Text(
                                      '7.',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 12,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.50,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 20,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 37,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://placehold.co/37x37"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 641,
                child: Container(
                  width: 327,
                  height: 37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 243,
                        top: 6,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFF666666)),
                              borderRadius: BorderRadius.circular(6),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 184,
                        top: 11,
                        child: Container(
                          width: 50,
                          height: 16,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 15,
                                top: 3,
                                child: Text(
                                  '45млн',
                                  style: TextStyle(
                                    color: Color(0xFF666666),
                                    fontSize: 11,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.88,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 172,
                          height: 37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 65,
                                top: 10,
                                child: SizedBox(
                                  width: 107,
                                  height: 13,
                                  child: SizedBox(
                                    width: 107,
                                    height: 13,
                                    child: Text(
                                      'Bezymnxa4',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.64,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 10,
                                child: SizedBox(
                                  width: 12,
                                  height: 13,
                                  child: SizedBox(
                                    width: 12,
                                    height: 13,
                                    child: Text(
                                      '8.',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 12,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.50,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 20,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 37,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://placehold.co/37x37"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 690,
                child: Container(
                  width: 327,
                  height: 37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 243,
                        top: 6,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFF666666)),
                              borderRadius: BorderRadius.circular(6),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 184,
                        top: 11,
                        child: Container(
                          width: 51,
                          height: 16,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 15,
                                top: 3,
                                child: Text(
                                  '33млн',
                                  style: TextStyle(
                                    color: Color(0xFF666666),
                                    fontSize: 11,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.88,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 172,
                          height: 37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 65,
                                top: 10,
                                child: SizedBox(
                                  width: 107,
                                  height: 13,
                                  child: SizedBox(
                                    width: 107,
                                    height: 13,
                                    child: Text(
                                      'Rayoshe',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.64,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 10,
                                child: SizedBox(
                                  width: 12,
                                  height: 13,
                                  child: SizedBox(
                                    width: 12,
                                    height: 13,
                                    child: Text(
                                      '9.',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 12,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.50,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 20,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 37,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://placehold.co/37x37"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 739,
                child: Container(
                  width: 333,
                  height: 37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 249,
                        top: 6,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFF666666)),
                              borderRadius: BorderRadius.circular(6),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 190,
                        top: 11,
                        child: Container(
                          width: 50,
                          height: 16,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 15,
                                top: 3,
                                child: Text(
                                  '32млн',
                                  style: TextStyle(
                                    color: Color(0xFF666666),
                                    fontSize: 11,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.88,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 178,
                          height: 37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 71,
                                top: 10,
                                child: SizedBox(
                                  width: 107,
                                  height: 13,
                                  child: SizedBox(
                                    width: 107,
                                    height: 13,
                                    child: Text(
                                      'Kentaro Miura',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.64,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 10,
                                child: SizedBox(
                                  width: 18,
                                  height: 13,
                                  child: SizedBox(
                                    width: 18,
                                    height: 13,
                                    child: Text(
                                      '10.',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 12,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.50,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 26,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 37,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://placehold.co/37x37"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 788,
                child: Container(
                  width: 330,
                  height: 37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 246,
                        top: 6,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFF666666)),
                              borderRadius: BorderRadius.circular(6),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 187,
                        top: 11,
                        child: Container(
                          width: 51,
                          height: 16,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 15,
                                top: 3,
                                child: Text(
                                  '30млн',
                                  style: TextStyle(
                                    color: Color(0xFF666666),
                                    fontSize: 11,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.88,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 175,
                          height: 37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 68,
                                top: 10,
                                child: SizedBox(
                                  width: 107,
                                  height: 13,
                                  child: SizedBox(
                                    width: 107,
                                    height: 13,
                                    child: Text(
                                      'Justin bieber <3',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.64,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 10,
                                child: SizedBox(
                                  width: 15,
                                  height: 13,
                                  child: SizedBox(
                                    width: 15,
                                    height: 13,
                                    child: Text(
                                      '11.',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 12,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.50,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 23,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 37,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://placehold.co/37x37"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 837,
                child: Container(
                  width: 332,
                  height: 37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 248,
                        top: 6,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFF666666)),
                              borderRadius: BorderRadius.circular(6),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 189,
                        top: 11,
                        child: Container(
                          width: 50,
                          height: 16,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 15,
                                top: 3,
                                child: Text(
                                  '27млн',
                                  style: TextStyle(
                                    color: Color(0xFF666666),
                                    fontSize: 11,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.88,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 177,
                          height: 37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 70,
                                top: 10,
                                child: SizedBox(
                                  width: 107,
                                  height: 13,
                                  child: SizedBox(
                                    width: 107,
                                    height: 13,
                                    child: Text(
                                      'Mishura526',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.64,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 10,
                                child: SizedBox(
                                  width: 18,
                                  height: 13,
                                  child: SizedBox(
                                    width: 18,
                                    height: 13,
                                    child: Text(
                                      '12.',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 12,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.50,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 25,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 37,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://placehold.co/37x37"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 886,
                child: Container(
                  width: 332,
                  height: 37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 248,
                        top: 6,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFF666666)),
                              borderRadius: BorderRadius.circular(6),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 189,
                        top: 11,
                        child: Container(
                          width: 50,
                          height: 16,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 15,
                                top: 3,
                                child: Text(
                                  '26млн',
                                  style: TextStyle(
                                    color: Color(0xFF666666),
                                    fontSize: 11,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.88,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 177,
                          height: 37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 70,
                                top: 10,
                                child: SizedBox(
                                  width: 107,
                                  height: 13,
                                  child: SizedBox(
                                    width: 107,
                                    height: 13,
                                    child: Text(
                                      'bopeshka',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.64,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 10,
                                child: SizedBox(
                                  width: 18,
                                  height: 13,
                                  child: SizedBox(
                                    width: 18,
                                    height: 13,
                                    child: Text(
                                      '13.',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 12,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.50,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 25,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 37,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://placehold.co/37x37"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 935,
                child: Container(
                  width: 332,
                  height: 37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 248,
                        top: 6,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFF666666)),
                              borderRadius: BorderRadius.circular(6),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 189,
                        top: 11,
                        child: Container(
                          width: 49,
                          height: 16,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 15,
                                top: 3,
                                child: Text(
                                  '19млн',
                                  style: TextStyle(
                                    color: Color(0xFF666666),
                                    fontSize: 11,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.88,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 177,
                          height: 37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 70,
                                top: 10,
                                child: SizedBox(
                                  width: 107,
                                  height: 13,
                                  child: SizedBox(
                                    width: 107,
                                    height: 13,
                                    child: Text(
                                      'Бу! Испугался? Не бойся',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 8,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 2.25,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 10,
                                child: SizedBox(
                                  width: 18,
                                  height: 13,
                                  child: SizedBox(
                                    width: 18,
                                    height: 13,
                                    child: Text(
                                      '14.',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 12,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.50,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 25,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 37,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://placehold.co/37x37"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 984,
                child: Container(
                  width: 331,
                  height: 37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 247,
                        top: 6,
                        child: Container(
                          width: 84,
                          height: 22.74,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFF666666)),
                              borderRadius: BorderRadius.circular(6),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 188,
                        top: 11,
                        child: Container(
                          width: 49,
                          height: 16,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 15,
                                top: 3,
                                child: Text(
                                  '14млн',
                                  style: TextStyle(
                                    color: Color(0xFF666666),
                                    fontSize: 11,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.88,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 176,
                          height: 37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 69,
                                top: 10,
                                child: SizedBox(
                                  width: 107,
                                  height: 13,
                                  child: SizedBox(
                                    width: 107,
                                    height: 13,
                                    child: Text(
                                      'MBAPPE',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.64,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 10,
                                child: SizedBox(
                                  width: 17,
                                  height: 13,
                                  child: SizedBox(
                                    width: 17,
                                    height: 13,
                                    child: Text(
                                      '15.',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 12,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w700,
                                        height: 1.50,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 24,
                                top: 0,
                                child: Container(
                                  width: 37,
                                  height: 37,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://placehold.co/37x37"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 298,
                top: 1039,
                child: Container(
                  width: 66,
                  height: 38,
                  decoration: ShapeDecoration(
                    color: Color(0xFF1E1E1E),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(5)),
                  ),
                ),
              ),
              Positioned(
                left: 333,
                top: 1051,
                child: Text(
                  '15',
                  style: TextStyle(
                    color: Color(0xFF666666),
                    fontSize: 16,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w300,
                    height: 0.88,
                  ),
                ),
              ),
              Positioned(
                left: 128,
                top: 391,
                child: Container(
                  width: 31,
                  height: 40,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 4,
                        top: 15,
                        child: Container(
                          width: 23.11,
                          height: 25,
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 31,
                          height: 31,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 31,
                                  height: 31,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 1.45,
                                top: 1.45,
                                child: Container(
                                  width: 28.09,
                                  height: 28.09,
                                  padding: const EdgeInsets.only(
                                    top: 8.17,
                                    left: 9.75,
                                    right: 10.09,
                                    bottom: 8.72,
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 8.24,
                                        height: 11.20,
                                        child: Stack(),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 240,
                top: 290,
                child: Container(
                  width: 112,
                  height: 112,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/112x112"),
                      fit: BoxFit.fill,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 311,
                top: 366,
                child: Container(
                  width: 31,
                  height: 40.67,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 4,
                        top: 15,
                        child: Container(
                          width: 23.73,
                          height: 25.67,
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 31,
                          height: 31,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 31,
                                  height: 31,
                                  child: FlutterLogo(),
                                ),
                              ),
                              Positioned(
                                left: 1.45,
                                top: 1.45,
                                child: Container(
                                  width: 28.09,
                                  height: 28.09,
                                  padding: const EdgeInsets.only(
                                    top: 8.17,
                                    left: 9.79,
                                    right: 9.96,
                                    bottom: 8.84,
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 8.34,
                                        height: 11.08,
                                        child: Stack(),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
